sylius_product:
    resources:
        product:
            classes:
                model: Locastic\SyliusRitamIntegrationPlugin\Entity\Product
                repository: Locastic\SyliusRitamIntegrationPlugin\Repository\ProductRepository